rem オートセーブ
del /q autosave\autosave_100.sve
ren autosave\autosave_99.sve autosave_100.sve
ren autosave\autosave_98.sve autosave_99.sve
ren autosave\autosave_97.sve autosave_98.sve
ren autosave\autosave_96.sve autosave_97.sve
ren autosave\autosave_95.sve autosave_96.sve
ren autosave\autosave_94.sve autosave_95.sve
ren autosave\autosave_93.sve autosave_94.sve
ren autosave\autosave_92.sve autosave_93.sve
ren autosave\autosave_91.sve autosave_92.sve
ren autosave\autosave_90.sve autosave_91.sve
ren autosave\autosave_89.sve autosave_90.sve
ren autosave\autosave_88.sve autosave_89.sve
ren autosave\autosave_87.sve autosave_88.sve
ren autosave\autosave_86.sve autosave_87.sve
ren autosave\autosave_85.sve autosave_86.sve
ren autosave\autosave_84.sve autosave_85.sve
ren autosave\autosave_83.sve autosave_84.sve
ren autosave\autosave_82.sve autosave_83.sve
ren autosave\autosave_81.sve autosave_82.sve
ren autosave\autosave_80.sve autosave_81.sve
ren autosave\autosave_79.sve autosave_80.sve
ren autosave\autosave_78.sve autosave_79.sve
ren autosave\autosave_77.sve autosave_78.sve
ren autosave\autosave_76.sve autosave_77.sve
ren autosave\autosave_75.sve autosave_76.sve
ren autosave\autosave_74.sve autosave_75.sve
ren autosave\autosave_73.sve autosave_74.sve
ren autosave\autosave_72.sve autosave_73.sve
ren autosave\autosave_71.sve autosave_72.sve
ren autosave\autosave_70.sve autosave_71.sve
ren autosave\autosave_69.sve autosave_70.sve
ren autosave\autosave_68.sve autosave_69.sve
ren autosave\autosave_67.sve autosave_68.sve
ren autosave\autosave_66.sve autosave_67.sve
ren autosave\autosave_65.sve autosave_66.sve
ren autosave\autosave_64.sve autosave_65.sve
ren autosave\autosave_63.sve autosave_64.sve
ren autosave\autosave_62.sve autosave_63.sve
ren autosave\autosave_61.sve autosave_62.sve
ren autosave\autosave_60.sve autosave_61.sve
ren autosave\autosave_59.sve autosave_60.sve
ren autosave\autosave_58.sve autosave_59.sve
ren autosave\autosave_57.sve autosave_58.sve
ren autosave\autosave_56.sve autosave_57.sve
ren autosave\autosave_55.sve autosave_56.sve
ren autosave\autosave_54.sve autosave_55.sve
ren autosave\autosave_53.sve autosave_54.sve
ren autosave\autosave_52.sve autosave_53.sve
ren autosave\autosave_51.sve autosave_52.sve
ren autosave\autosave_50.sve autosave_51.sve
ren autosave\autosave_49.sve autosave_50.sve
ren autosave\autosave_48.sve autosave_49.sve
ren autosave\autosave_47.sve autosave_48.sve
ren autosave\autosave_46.sve autosave_47.sve
ren autosave\autosave_45.sve autosave_46.sve
ren autosave\autosave_44.sve autosave_45.sve
ren autosave\autosave_43.sve autosave_44.sve
ren autosave\autosave_42.sve autosave_43.sve
ren autosave\autosave_41.sve autosave_42.sve
ren autosave\autosave_40.sve autosave_41.sve
ren autosave\autosave_39.sve autosave_40.sve
ren autosave\autosave_38.sve autosave_39.sve
ren autosave\autosave_37.sve autosave_38.sve
ren autosave\autosave_36.sve autosave_37.sve
ren autosave\autosave_35.sve autosave_36.sve
ren autosave\autosave_34.sve autosave_35.sve
ren autosave\autosave_33.sve autosave_34.sve
ren autosave\autosave_32.sve autosave_33.sve
ren autosave\autosave_31.sve autosave_32.sve
ren autosave\autosave_30.sve autosave_31.sve
ren autosave\autosave_29.sve autosave_30.sve
ren autosave\autosave_28.sve autosave_29.sve
ren autosave\autosave_27.sve autosave_28.sve
ren autosave\autosave_26.sve autosave_27.sve
ren autosave\autosave_25.sve autosave_26.sve
ren autosave\autosave_24.sve autosave_25.sve
ren autosave\autosave_23.sve autosave_24.sve
ren autosave\autosave_22.sve autosave_23.sve
ren autosave\autosave_21.sve autosave_22.sve
ren autosave\autosave_20.sve autosave_21.sve
ren autosave\autosave_19.sve autosave_20.sve
ren autosave\autosave_18.sve autosave_19.sve
ren autosave\autosave_17.sve autosave_18.sve
ren autosave\autosave_16.sve autosave_17.sve
ren autosave\autosave_15.sve autosave_16.sve
ren autosave\autosave_14.sve autosave_15.sve
ren autosave\autosave_13.sve autosave_14.sve
ren autosave\autosave_12.sve autosave_13.sve
ren autosave\autosave_11.sve autosave_12.sve
ren autosave\autosave_10.sve autosave_11.sve
ren autosave\autosave_9.sve autosave_10.sve
ren autosave\autosave_8.sve autosave_9.sve
ren autosave\autosave_7.sve autosave_8.sve
ren autosave\autosave_6.sve autosave_7.sve
ren autosave\autosave_5.sve autosave_6.sve
ren autosave\autosave_4.sve autosave_5.sve
ren autosave\autosave_3.sve autosave_4.sve
ren autosave\autosave_2.sve autosave_3.sve
ren autosave\autosave_1.sve autosave_2.sve
copy !serversave! autosave\autosave_1.sve
nettool -p !nettoolpass! -s !serverip! force-sync
echo [!DATE! !TIME!]オートセーブしました。